name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set build output directory
      id: build-output-dir
      shell: bash
      run: |
        echo "path=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcmocka-dev
  
    - name: Configure CMake
      run: >
        cmake -B ${{ steps.build-output-dir.outputs.path }} -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.build-output-dir.outputs.path }}

    - name: Test
      working-directory: ${{ steps.build-output-dir.outputs.path }}
      run: ctest --output-on-failure
